<?php

namespace AppBundle\Repository;

use AppBundle\Document\Item;
use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends DocumentRepository
{

    /**
     * search the item in item collection.
     *
     * @param Item item  the item container with the title searched
     * @return string|null The transformed input
     *
     */
    public function searchByTitle(Item $item)
    {
        /*
         *  I did not found a more efficent way to do a like operation with doctrine+mongodb...
         *
         */
        return $this->createQueryBuilder()
            ->field('title')->equals(new \MongoRegex('/.*'.$item->getTitle().'.*/i'))
            ->getQuery()
            ->execute();
    }


    /**
     * Display last x item discovered
     *
     * @param int $limit  result's limit (NB This is set with  "latest_home_number" param in parameters.yml
     *
     * @return string|null The transformed input
     *
     * @throws \NotFoundHttpException When imdbid is not provided or item is not longer available
     */
    public function getLatestItem($limit)
    {
        return $this->findBy([], ['_id' => '-1'], $limit);
    }

}